<?php
$plugin = array(
  'title'     => t('Panels Everywhere site template'),
  'theme'     => 'site_template',
  'icon'      => 'site_template.png',
  'category'  => 'Panels Everywhere',
  'regions' => array(
    'header'            => t('Header'),
    'header_block'      => t('Header blocks'),
    'help'              => t('Help'),
    'content'           => t('Main content'),
    'footer'            => t('Footer'),
  ),
);
